language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
stages:
  - name: Test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: Tag and Bump
    if: (type IN (push) AND branch = develop)
jobs:
  include:
    - stage: Test
      script:
        - yarn lint
    - script:
        - travis_wait yarn ci-test
        - travis_wait yarn codecov
    - stage: Tag and Bump
      script:
        - yarn bump
        - git config user.email ${GITHUB_EMAIL}
        - git config user.name ${GITHUB_USER}
        - git push --follow-tags "https://${GITHUB_TOKEN}@${GITHUB_REPO}" develop
