language: node_js
node_js: '8.11.2'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
stages:
  - name: Test
    if: (type IN (pull_request)) OR (type IN (push) AND branch = master)
  - name: Publish Schema
    if: (type IN (push))
jobs:
  include:
    - stage: Test
      script:
        - yarn lint
    - script:
        - travis_wait yarn ci-test
        - travis_wait yarn codecov
    - stage: Publish Schema
      script: ENGINE_API_KEY=$ENGINE_API_KEY npx apollo schema:publish --endpoint=http://localhost:4000
